### ISSUE TITLE
Add promises support

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#98]
Apart from callbacks, use promises in the base classes to provide a simple interface to use yamp.

This will require designing on how the promises interface will work along with the current callbacks (and if it is possible)

**Comment by kbariotis** [comment]
Hello there,

I would suggest converting all private API to use only Promises. The public API then will use the promisified functions and only when it needs to return, will decide whether it should call the callback function provided or return a Promise instead.

How does it sound? I could work on it. Thank you.

**Comment by angrykoala** [comment]
Hi @kbariotis That sounds interesting. What would be the advantage of promising all the internal API?

**Comment by kbariotis** [comment]
@angrykoala There is no way for returning from a callback. (I'm sure there is a way but I am not aware of it.) E.g. the [renderFile](https://github.com/angrykoala/yamp/blob/master/app/renderer.js#L91) won't be able to return a Promise object due to its callbacks chain. By Promisifying the internal API we would be able to either return a Promise object by the end of the function or call the given callback function.

Please correct me if I'm wrong.

Another way would be to use [async](http://caolan.github.io/async/) helpers everywhere in order to orchestrate the callback chains but since the goal is to promisify the API, implementing promise would be a better way to take.

Thank you and I would love to hear other's opinions

**Comment by angrykoala** [comment]
As far as I know (I don't usually use promises) it is possible to create (and return) a new Promise on the top level of the API and resolve the promise at the end of the callback without promising everything in the middle:
eg:

``` js
renderFile(files, options, done) {
let p=new Promise(...)
//some code here
    this.fileOutput(res, renderOptions.outputFilename,function(err,res){
   //last callback in chain
    p.resolve();
   done():
   }
//some code here
return p;
}
```

However, I'm not sure (hence the question label) if there are advantages on promising part (or all the API as you suggest)

I'm not sure if promising or callbacks is the best way to code the internal API, but anyway we should be able to return promise and callback (optionally) in the public interface. I would like to avoid using dependencies for this (async or any promise library)

**Comment by kbariotis** [comment]
Yes @angrykoala you are right. Creating and returning a promise in the public API will be much easier and simple. I will try to make a PR. Thank you
